import LegalSection from "./LegalSection";

export default function Terms() {
  return (
    <LegalSection
      id="terms"
      eyebrow="Terms of Service"
      heading="Terms of Service"
      lastUpdated="April 26, 2026"
    >
      <p>
        These terms describe the deal between you and Reverie Dreams when
        you use the Reverie iOS app or this website. They&apos;re written in
        plain English on purpose. By using Reverie you&apos;re agreeing to
        them.
      </p>

      <h3 className="legal-h">Acceptance</h3>
      <p>
        By creating an account, downloading the app, or otherwise using
        Reverie, you agree to these terms and to our Privacy Policy. If you
        don&apos;t agree, please don&apos;t use Reverie.
      </p>

      <h3 className="legal-h">Account</h3>
      <ul className="legal-list">
        <li>You must be at least 13 years old to use Reverie.</li>
        <li>
          You must provide accurate information when signing up. One account
          per person.
        </li>
        <li>
          You&apos;re responsible for keeping your account credentials safe
          and for activity that happens under your account.
        </li>
      </ul>

      <h3 className="legal-h">Your content</h3>
      <p>
        Dreams, comments, profile content, and anything else you put into
        Reverie are <strong>yours</strong>. You own your dreams. By
        submitting content to Reverie you grant us a worldwide, non-
        exclusive, royalty-free license to host, store, transcribe,
        process, and display that content for the sole purpose of running
        the app for you (and, for content you choose to mark public, of
        showing it to other Reverie users on the Feed). This license ends
        when you delete the content or your account, except to the extent
        we&apos;re legally required to retain it.
      </p>
      <p>
        You&apos;re responsible for what you post. Don&apos;t submit
        anything you don&apos;t have the right to share.
      </p>

      <h3 className="legal-h">Acceptable use</h3>
      <p>You agree not to:</p>
      <ul className="legal-list">
        <li>
          Harass, threaten, or target other users; post hate speech or
          incitements to violence.
        </li>
        <li>
          Post illegal content, sexual content involving minors, or content
          that violates someone else&apos;s rights.
        </li>
        <li>Spam the Feed, scrape the app, or attempt to abuse the API.</li>
        <li>
          Impersonate another person or misrepresent your affiliation with
          anyone.
        </li>
        <li>
          Try to break, reverse-engineer, or overload the service.
        </li>
      </ul>
      <p>
        We may remove content or suspend accounts that violate these rules.
      </p>

      <h3 className="legal-h">AI-generated content disclaimer</h3>
      <p>
        Reverie&apos;s interpretations, symbolism notes, and Oracle responses
        are <strong>generated by AI</strong> for purposes of reflection,
        creativity, and entertainment. They are not — and are not intended
        to be — medical, psychological, psychiatric, or therapeutic advice.
        AI can be wrong. If you&apos;re struggling with your mental health,
        please speak to a qualified professional, not a dream app.
      </p>

      <h3 className="legal-h">Service availability</h3>
      <p>
        Reverie is provided <em>as is</em> and <em>as available</em>. We do
        our best to keep the service running, but features may change,
        break, or go away. Expect occasional downtime. We don&apos;t
        guarantee uptime, perfection, or that any specific feature will
        keep working forever.
      </p>

      <h3 className="legal-h">Termination</h3>
      <p>
        You can delete your account at any time using the &ldquo;Forget
        Me&rdquo; option in the app. We may suspend or terminate accounts
        that violate these terms or that pose a risk to other users or to
        the service. Where reasonable, we&apos;ll tell you why.
      </p>

      <h3 className="legal-h">Limitation of liability</h3>
      <p>
        To the maximum extent permitted by law, Reverie Dreams, its
        contributors, and its providers are not liable for indirect,
        incidental, special, consequential, or punitive damages, or any
        loss of data or content, arising out of your use of the app. Our
        total liability for any claim related to the service is limited to
        the amount you paid us for the service in the twelve months before
        the claim, or, if you paid nothing, fifty Canadian dollars.
      </p>
      <p>
        Nothing in these terms limits any rights that can&apos;t legally be
        limited (for example, statutory consumer rights in your region).
      </p>

      <h3 className="legal-h">Governing law</h3>
      <p>
        These terms are governed by the laws of the Province of Ontario,
        Canada, and the federal laws of Canada that apply there. Disputes
        will be handled in the courts of Ontario, unless the law where you
        live requires otherwise.
      </p>

      <h3 className="legal-h">Changes to these terms</h3>
      <p>
        We may update these terms as Reverie evolves. When we make material
        changes, we&apos;ll update the &ldquo;Last updated&rdquo; date and,
        where appropriate, notify you in the app. Continuing to use Reverie
        after a change means you accept the updated terms.
      </p>

      <h3 className="legal-h">Contact</h3>
      <p>
        Questions about these terms?{" "}
        <a className="legal-link" href="mailto:hello@reveriedreams.com">
          hello@reveriedreams.com
        </a>
        .
      </p>
    </LegalSection>
  );
}
